
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, '../.env.local');

// Quick env parser
const envConfig: any = {};
try {
    const envFile = fs.readFileSync(envPath, 'utf8');
    envFile.split('\n').forEach(line => {
        const [key, value] = line.split('=');
        if (key && value) envConfig[key.trim()] = value.trim();
    });
} catch (e) {
    console.log('No .env.local found');
}

const supabaseUrl = envConfig['VITE_SUPABASE_URL'];
const supabaseKey = envConfig['VITE_SUPABASE_ANON_KEY'];
// Note: Normally table creation requires service_role key, but if RLS is off or anon has permissions, it might work.
// However, creating tables usually needs SQL Editor or migration tool. 
// Since I cannot access SQL Editor directly, I will try to use the `rpc` if available or just assume the user can run SQL.
// But wait, I have `service_role` key in some projects? No, usually only Anon key in client app.
// If I cannot create table via client, I must ask USER to run SQL in Supabase Dashboard.
// Let's first check if the table exists.

const supabase = createClient(supabaseUrl, supabaseKey);

async function createTable() {
    console.log("Checking if 'recent_works' table exists...");

    const { data, error } = await supabase.from('recent_works').select('id').limit(1);

    if (error) {
        console.log("Table 'recent_works' likely does not exist or permission denied:", error.message);
        console.log("\nPlease run the following SQL in your Supabase SQL Editor to create the table:\n");
        console.log(`
-- Create recent_works table
CREATE TABLE IF NOT EXISTS public.recent_works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en TEXT,
    title_kr TEXT,
    description TEXT,
    category TEXT,
    column_index INTEGER DEFAULT 1, -- 1, 2, or 3
    scroll_speed FLOAT DEFAULT 1.0, -- Speed multiplier
    thumbnail_url TEXT,
    content_blocks JSONB DEFAULT '[]'::jsonb, -- Stores the detailed layout content
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.recent_works ENABLE ROW LEVEL SECURITY;

-- Create policies (Adjust as needed for public read / auth write)
CREATE POLICY "Enable read access for all users" ON public.recent_works FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.recent_works FOR INSERT WITH CHECK (true); -- Simplified for dev
CREATE POLICY "Enable update for authenticated users only" ON public.recent_works FOR UPDATE USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON public.recent_works FOR DELETE USING (true);

-- Grant permissions
GRANT ALL ON TABLE public.recent_works TO anon;
GRANT ALL ON TABLE public.recent_works TO authenticated;
GRANT ALL ON TABLE public.recent_works TO service_role;
     `);
    } else {
        console.log("Table 'recent_works' already exists.");
    }
}

createTable();
